# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 220)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.m_gBoxInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.m_gBoxInfo.setEnabled(True)
        self.m_gBoxInfo.setObjectName("m_gBoxInfo")
        self.m_lblUsername = QtWidgets.QLabel(self.m_gBoxInfo)
        self.m_lblUsername.setGeometry(QtCore.QRect(5, 24, 101, 31))
        self.m_lblUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_lblUsername.setObjectName("m_lblUsername")
        self.m_lblPwd = QtWidgets.QLabel(self.m_gBoxInfo)
        self.m_lblPwd.setGeometry(QtCore.QRect(5, 54, 101, 31))
        self.m_lblPwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_lblPwd.setObjectName("m_lblPwd")
        self.m_txtUsername = QtWidgets.QLineEdit(self.m_gBoxInfo)
        self.m_txtUsername.setGeometry(QtCore.QRect(110, 30, 101, 22))
        self.m_txtUsername.setObjectName("m_txtUsername")
        self.m_txtPwd = QtWidgets.QLineEdit(self.m_gBoxInfo)
        self.m_txtPwd.setGeometry(QtCore.QRect(110, 60, 101, 22))
        self.m_txtPwd.setObjectName("m_txtPwd")
        self.m_txtPwd.setEchoMode(QLineEdit.Password)
        self.verticalLayout.addWidget(self.m_gBoxInfo)
        self.m_btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.m_btnLogin.setObjectName("m_btnLogin")
        self.m_btnLogin.clicked.connect(self.OnButtonLoginClicked)
        self.verticalLayout.addWidget(self.m_btnLogin)
        self.m_btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.m_btnClear.setObjectName("m_btnClear")
        self.m_btnClear.clicked.connect(self.OnButtonClearClicked)
        self.verticalLayout.addWidget(self.m_btnClear)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 24))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.isLoggedIn = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.m_gBoxInfo.setTitle(_translate("MainWindow", "User Information"))
        self.m_lblUsername.setText(_translate("MainWindow", "Username : "))
        self.m_lblPwd.setText(_translate("MainWindow", "Password : "))
        self.m_btnLogin.setText(_translate("MainWindow", "Login"))
        self.m_btnClear.setText(_translate("MainWindow", "Clear"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

    def OnButtonClearClicked(self):
        self.m_txtUsername.setText("")
        self.m_txtPwd.setText("")

    def OnButtonLoginClicked(self):
        name = self.m_txtUsername.text()
        self.key = "123456"

        if (self.key == self.m_txtPwd.text()):
            print(f"{name} is logged in.")
            self.isLoggedIn = True
        else:
            print("Invalid username or password.")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
